Added Workflow

diff --git a/.github/workflows/leshka.yml b/.github/workflows/leshka.yml
--- a/.github/workflows/leshka.yml
+++ b/.github/workflows/leshka.yml
@@ -31,22 +31,19 @@ jobs:
       - name: Build with Maven
         run: mvn -B clean install --file pom.xml
 
-      - name: Run tests with Maven and generate test report
-        run: mvn surefire-report:report
-
-      - name: Check test results
-        id: test_result
+      - name: Run tests with Maven
+        id: run_tests
         run: |
-          FILE=target/surefire-reports/test-summary.txt
-          if grep -q "FAILURE!" "$FILE"; then
-            echo "::set-output name=failed::true"
-            echo "::set-output name=failed_tests::$(grep 'Tests run:' "$FILE" | grep -o 'Failures:[^,]*' | grep -o '[0-9]*')" 
-          else
-            echo "::set-output name=failed::false"
-          fi
+          set -e
+          mvn -B test --file pom.xml
+          echo "TEST_RESULT=$(grep -o 'Failures:[^,]*' target/surefire-reports/*.txt | grep -o '[0-9]\+')" >> $GITHUB_ENV
+
+      - name: Set test result outputs
+        id: set_test_result
+        run: echo "::set-output name=failed_tests::$TEST_RESULT"
 
       - name: Send Telegram notification on success
-        if: steps.test_result.outputs.failed == 'false'
+        if: steps.set_test_result.outputs.failed_tests == '0'
         uses: appleboy/telegram-action@master
         with:
           to: ${{ secrets.TELEGRAM_CHAT_ID }}
@@ -54,9 +51,9 @@ jobs:
           message: "Всё ок"
 
       - name: Send Telegram notification on failure
-        if: steps.test_result.outputs.failed == 'true'
+        if: steps.set_test_result.outputs.failed_tests != '0'
         uses: appleboy/telegram-action@master
         with:
           to: ${{ secrets.TELEGRAM_CHAT_ID }}
           token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-          message: "Неудавшиеся тесты: ${{ steps.test_result.outputs.failed_tests }}"
+          message: "Неудавшиеся тесты: ${{ steps.set_test_result.outputs.failed_tests }}"
